development:
  facebook_key: 129652407201708
  facebook_secret: 3576504b0f44911f7d1342fc1460d389
  twitter_key: cJbrNjPg2X7rjVPpP6eOOw
  twitter_secret: Jfqbn2QETFbcEq07erps0P6FM41JAQSIX2YZirS4I

test:
  facebook_key: 129652407201708
  facebook_secret: 3576504b0f44911f7d1342fc1460d389
  twitter_key: cJbrNjPg2X7rjVPpP6eOOw
  twitter_secret: Jfqbn2QETFbcEq07erps0P6FM41JAQSIX2YZirS4I

production:
  facebook_key: 871872409507898
  facebook_secret: a1ddedfb40374875e7269cbb6a1cb7eb 
  twitter_key: kCk5xY82VLtqZq4u6OjKRqwiI
  twitter_secret: H0D27rMtmGvZMKpNQA7Rh2b5sZGHrK1nDMVlaRtdAVfwcJuyJn